name: flutter_farmacia
description: Projeto Farmácia com Supabase
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # ADICIONE ESTAS DUAS LINHAS ↓
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  flutter_dotenv: ^5.1.0
  convex_bottom_bar: ^3.2.0
  supabase_flutter: ^2.10.3
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.2

  excel: ^4.0.0
  open_filex: ^4.3.2
  pdf: ^3.11.0
  printing: ^5.12.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
  #   - assets/images/